name: umd
favicon: null
layout_spectrum: 0.17786305164918303
typography_spectrum: 0.0530286175198853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9624806884676218
  lightness: 0.3869288917630911
  saturation: 0.4047946184873581
  rhythmicContrast: 0.7470481521449983
purpose: []
