name: umd
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16494
title: umd design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e0db'
    - '#ffffff'
    - '#f7941d'
    - '#f69c30'
    - '#eaeae6'
  brandStrength: 0.9624806884676218
  lightness: 0.3869288917630911
  saturation: 0.4047946184873581
  rhythmicContrast: 0.7470481521449983
purpose: []
