name: umd
favicon: null
layout_spectrum: 0.48754
typography_spectrum: 0.16494
title: umd design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e0db'
    - '#ffffff'
    - '#f7941d'
    - '#f69c30'
    - '#eaeae6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
